In [1]:
from gym_pybullet_drones.utils.enums import ObservationType, ActionType

In [2]:
DEFAULT_OBS = ObservationType('kin') # 'kin' or 'rgb'
DEFAULT_ACT = ActionType('one_d_rpm') # 'rpm' or 'pid' or 'vel' or 'one_d_rpm' or 'one_d_pid'

In [3]:
DEFAULT_ACT

<ActionType.ONE_D_RPM: 'one_d_rpm'>

In [8]:
DEFAULT_OBS

<ObservationType.KIN: 'kin'>

In [27]:
for i in range(4):
    print(i, end=",")

0,1,2,3,

In [12]:
import numpy as np

In [17]:
NUM_DRONES = 5
NEIGHBOURHOOD_RADIUS = 30

In [25]:
def _getAdjacencyMatrix():
        """Computes the adjacency matrix of a multi-drone system.

        Attribute NEIGHBOURHOOD_RADIUS is used to determine neighboring relationships.

        Returns
        -------
        ndarray
            (NUM_DRONES, NUM_DRONES)-shaped array of 0's and 1's representing the adjacency matrix 
            of the system: adj_mat[i,j] == 1 if (i, j) are neighbors; == 0 otherwise.

        """
        adjacency_mat = np.identity(NUM_DRONES)
        for i in range(NUM_DRONES-1):
            for j in range(NUM_DRONES-i-1):
                # print((i,j), end=",")
                if True: #np.linalg.norm(pos[i, :]-pos[j+i+1, :]) < NEIGHBOURHOOD_RADIUS:
                    adjacency_mat[i, j+i+1] = adjacency_mat[j+i+1, i] = 1
        print(adjacency_mat)
        return True #adjacency_mat

In [26]:
_getAdjacencyMatrix()

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


True

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])